services:
  - type: web
    name: flask-chatroom
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y build-essential
      pip install -r requirements.txt
    startCommand: gunicorn app:app
